boot.o: boot.S multiboot.h x86_desc.h types.h
idt_ex_handler.o: idt_ex_handler.S idt_ex_handler.h
x86_desc.o: x86_desc.S x86_desc.h types.h
file_system.o: file_system.c file_system.h types.h lib.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h lib.h types.h x86_desc.h idt_ex_handler.h keyboard.h \
  rtc.h i8259.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h rtc.h keyboard.h paging.h file_system.h
keyboard.o: keyboard.c keyboard.h lib.h types.h idt_ex_handler.h idt.h \
  x86_desc.h rtc.h terminal.h i8259.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h x86_desc.h types.h
rtc.o: rtc.c rtc.h lib.h types.h idt_ex_handler.h idt.h x86_desc.h \
  keyboard.h i8259.h
terminal.o: terminal.c terminal.h keyboard.h types.h lib.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h rtc.h file_system.h \
  terminal.h keyboard.h
