asm_linkage.o: asm_linkage.S asm_linkage.h
boot.o: boot.S multiboot.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
file_system.o: file_system.c file_system.h types.h lib.h system_calls.h \
  x86_desc.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h lib.h types.h x86_desc.h asm_linkage.h keyboard.h \
  rtc.h system_calls.h i8259.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h rtc.h keyboard.h paging.h file_system.h system_calls.h \
  pit.h sound.h mouse.h terminal.h
keyboard.o: keyboard.c keyboard.h lib.h types.h asm_linkage.h idt.h \
  x86_desc.h rtc.h system_calls.h terminal.h i8259.h
lib.o: lib.c lib.h types.h
mouse.o: mouse.c mouse.h types.h asm_linkage.h idt.h lib.h x86_desc.h \
  keyboard.h rtc.h system_calls.h i8259.h
paging.o: paging.c paging.h x86_desc.h types.h
pit.o: pit.c pit.h lib.h types.h sound.h rtc.h asm_linkage.h idt.h \
  x86_desc.h keyboard.h system_calls.h i8259.h
rtc.o: rtc.c rtc.h lib.h types.h asm_linkage.h idt.h x86_desc.h \
  keyboard.h system_calls.h i8259.h
sound.o: sound.c pit.h lib.h types.h sound.h rtc.h asm_linkage.h idt.h \
  x86_desc.h keyboard.h system_calls.h i8259.h
system_calls.o: system_calls.c x86_desc.h types.h system_calls.h paging.h \
  lib.h rtc.h file_system.h terminal.h keyboard.h idt.h
terminal.o: terminal.c terminal.h keyboard.h types.h lib.h rtc.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h rtc.h file_system.h \
  terminal.h keyboard.h paging.h system_calls.h
